language: objective-c
before_install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
    - xcodebuild -workspace 'THCCoreData.xcworkspace' -scheme 'THCCoreData' -sdk 'iphonesimulator' -configuration Debug clean test | xcpretty -c
