language: objective-c
osx_image: xcode63
branches:
  only:
    - master
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
- gem install xcpretty -N
script:
- set -o pipefail
- xcodebuild -workspace 'THCCoreData.xcworkspace' -scheme 'THCCoreData' -sdk 'iphonesimulator' -configuration Release clean test | xcpretty -c
